name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Commit & Push to dist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git checkout -B dist
          git add -f dist/*
          git commit -m "Build generated at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes"
          git push origin dist --force || git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} dist --force